### ISSUE TITLE
你好，我想请教一下，这个库好像placeHolder和本地图片无法显示？

### ISSUE THREAD

**Issue by hsf25737** [liweijieok/WeChatGroupAvatar#1]

**Comment by liweijieok** [comment]
可以的啊，placeholder需要传入一个bitmap或者是一个资源文件，目前不支持placeholder传入本地文件。假如是需要传入本地文件，那么先试用一下BitmapFactory构建一个传入即可。

假如是本地图片作为头，即传入的urls，那么他的加载是在config()配置的时候用户自己去决定如何加载bitmap的，与lib无关。
